### ISSUE TITLE
Withdrawals are broken on https://bridge.stx.eco/withdraw?net=testnet

### ISSUE THREAD

**Issue by netrome** [Stacks-Builders/sbtc-bridge-web#187] opened 2023-07-17 10:06 UTC
When trying to sign a withdrawal PSBT I'm getting the following error: `Uncaught (in promise) TypeError: piTx.addressInfo is undefined`

![image](https://github.com/Stacks-Builders/sbtc-bridge-web/assets/22524681/3d92bc55-39e0-4d40-8e56-6e7a54a2ae58)

**Comment by radicleart** [comment] 2023-07-17 10:20
@netrome thanks for reporting. I just restarted the node application and tested a withdrawal which sent this [transaction](https://mempool.space/testnet/address/tb1phrytqefvk2z3553hf3av63ccr6crr686t33gs0mrdcx5le546m9qx7uvcl)

I think the issue is a bug in my deployment pipeline - [environment variables on the target machine not overriding the environment from the deployer machine](https://github.com/Stacks-Builders/sbtc-bridge-web/issues/188)

I'll close this in favour of that issue but please feel free to re-open this if you continue to have problems with withdrawing - although I think the manual restart of the server should mean its good for now.

**Comment by netrome** [comment] 2023-07-17 12:27
Weird. Something is still not working. I can sign the transactions, but they don't end up being broadcasted. The only warning I'm getting in the UI is `Empty string passed to getElementById()`

**Comment by netrome** [comment] 2023-07-17 12:30
@radicleart I'm not authorized to re-open this issue, but I'd love to get some help understanding why my transaction is not broadcasted.

**Comment by radicleart** [comment] 2023-07-17 16:01
Reopening to investigate broadcast issue

**Comment by netrome** [comment] 2023-07-17 16:05
> Reopening to investigate broadcast issue

Thank you!

**Closed** 2023-07-21 14:37 UTC
